blogger/urls.py
from django.urls import path
from . import views

app_name='blogger'
urlpatterns=[
	path('',views.IndexView.as_view(),name='index'),
	path('registeration/',views.registeration,name='registeration'),
	path('<int:pk>/',views.DetailView.as_view(),name='details'),
	path('login/',views.login,name='login'),
	path('logout/',views.logout,name='logout'),
	path('myblogs/',views.myblogs,name='myblogs'),
	path('addblog/',views.AddblogView.as_view(),name='addblog'),
	path('<int:pk>/edit/',views.UpdateBlogView.as_view(),name='editblog'),
	path('<int:pk>/delete/',views.DeleteBlogView.as_view(),name='deleteblog'),
	path('addcategory/',views.AddcategoryView.as_view(),name='addcategory'),
	path('category/<str:cats>/',views.CategoryView,name='category'),
	#path('filter/',views.FilterList,name='filter'),
	path('search/',views.AjaxHandlerView,name='search')
	]

myblog/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
	path('',include('blogger.urls')),
    path('admin/', admin.site.urls),
]

blogger/models.py
from django.db import models
from django.urls import reverse
import django
from django.contrib.auth.models import User
from django.http import HttpResponse 

# Create your models here.
class Category(models.Model):
	name=models.CharField(max_length=250,unique=True,default="")
	
	def __str__(self):
		return self.name
	def get_absolute_url(self):
		return reverse('blogger:index')
 

class Blog(models.Model):
	
	blog_name=models.CharField(max_length=100)
	author=models.ForeignKey(User,on_delete=models.CASCADE,null="true")
	date=models.DateTimeField(default=django.utils.timezone.now())
	blog_text=models.TextField()
	category=models.ForeignKey(Category,on_delete=models.CASCADE)

	def __str__(self):
		return self.blog_name

	def publish_date(self):
		return date
	def get_absolute_url(self):
		return reverse('blogger:index')

blogger/forms.py
from django.forms import ModelForm
from django.contrib.auth.models import User,auth
from django.contrib.auth.forms import UserCreationForm
from django import forms
from .models import Blog,Category

choices=Category.objects.all().values_list('name','name')
cats=[]
for i in choices:
    cats.append(i)

class CreateUserForm(UserCreationForm):
    """docstring for CreateUserForm"""
    class Meta:
        model = User
        fields=['username','email','password1','password2']

class BlogForm(forms.ModelForm):
    class Meta:
        model=Blog
        fields=('blog_name','category','blog_text')
        
        widgets={
            'blog_name':forms.TextInput(attrs={'class':'form-control'}),
            #'date':forms.DateTimeInput(attrs={'class':'form-control'}),
            # 'author':forms.Select(attrs={'class':'form-control'}),
            'category':forms.Select(attrs={'class':'form-control'}),
            'blog_text':forms.Textarea(attrs={'class':'form-control form-group-row'})
        }
        
            
class UpdateBlogForm(forms.ModelForm):
    class Meta:
        model=Blog
        fields=('blog_name','category','blog_text')

        widgets={
            'blog_name':forms.TextInput(attrs={'class':'form-control'}),
            #'date':forms.DateTimeInput(attrs={'class':'form-control'}),
            'category':forms.Select(attrs={'class':'form-control'}),
            'blog_text':forms.Textarea(attrs={'class':'form-control'})
        }

blogger/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponseRedirect
from django.forms import inlineformset_factory
from django.urls import reverse,reverse_lazy
from django.views import generic
from .models import Blog, Category
from django.contrib import messages
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.models import User,auth
from django.contrib.auth import authenticate
from django.contrib.auth.forms import UserCreationForm
from .forms import CreateUserForm, BlogForm,UpdateBlogForm
from django.contrib import messages
from django.core import serializers
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from .filters import BlogFilter
from django.conf import settings
from django.core.mail import send_mail,EmailMessage
import django_filters
from braces import views
from django.utils import timezone
from django.template.loader import render_to_string
from django.http import JsonResponse
from django.db.models import Q
# Create your views here.	
# def search(request):

	
# 	query=request.GET['query']

# 	if len(query)>78:
# 		allPosts = Blog.object.none()
# 	else:
# 		allPostsTitle = Blog.objects.filter(blog_name__icontains=query)
# 		allPostsContent = Blog.objects.filter(blog_text__icontains=query)
# 		allPosts = allPostsTitle.union(allPostsContent)

# 	if allPosts.count() != 0:
# 		params = {'allPosts': allPosts, 'query':query}
# 		page = render_to_string("include/results.html", params)
# 		return JsonResponse({'status': 'success', 'response': page})
# 	else:
# 		messages.warning(request, "No search result found. please refine your query")
# 		return JsonResponse({'status': 'fail'})
# def Ajaxsearch(request):
# 	ctx={}
# 	url_parameter=request.GET.get("q")
# 	if url_parameter:
# 		blogs=Blog.objects.filter(name__icontains=url_parameter)
# 	else:
# 		blogs=Blog.objects.all()
# 	ctx['blogs']=blogs
# 	if request.is_ajax():
# 		html=render_to_string(template_name="blogger/results.html",
# 		context={'blogs':blogs})
# 		data_dict={"html_from_view":html}
# 		return JsonResponse(data=data_dict,safe=False)

# 	return render(request,"blogger/search.html",context=ctx)


class IndexView(generic.ListView,views.JSONResponseMixin, views.AjaxResponseMixin):
	template_name='blogger/index.html'
	model=Blog
	order_by=['-date']
	paginate_by=5

	def get_queryset(self,**kwargs):
		queryset=BlogFilter(self.request.GET,queryset=Blog.objects.all().order_by('-date'))
		return queryset.qs

	def get_context_data(self,**kwargs):
		context=super().get_context_data(**kwargs)
		context['filter']=BlogFilter(self.request.GET,queryset=self.get_queryset())
		return context

	# def get(self,request,*args,**kwargs):
	# 	category=request.GET.get('category')
	# 	q=request.GET.get('q')
	# 	context=self.get_context_data()
	# 	print(context)
	# 	if request.is_ajax():
	# 		context=self.get_context_data()
	# 		return JsonResponse({'context':context},status=200)
	# 	return render(request,'blogger/index.html',context)


	# def get(self, request, *args, **kwargs):
	# 	ajax_list_partial = self.ajax_list_partial
	# 	self.object_list = super().get_queryset()
	# 	context = super().get_context_data(**kwargs)
	# 	if not ajax_list_partial:
	# 		raise TemplateDoesNotExist("No ajax__list_partial provided {}".format(self))
	# 		if request.is_ajax():
	# 			html_form = render_to_string(self.ajax__list_partial, context, request)
	# 			return JsonResponse({'html_form': html_form})
	# 		return super().get(request, *args, **kwargs)
	# def render_to_response(self):
	# 	return self.render_json_response(context)
	# def get_ajax(self,request):
	# 	import pdb;pdb.set_trace()
	# 	context_d=self.get_context_data()
	# 	return self.render_json_response(context_d)
def AjaxHandlerView(request):
	if request.method=='GET':
		# import pdb;pdb.set_trace()
		blog_list=Blog.objects.all().order_by("-date")
		
		blog_filter=BlogFilter(request.GET,queryset=blog_list)	
		if request.is_ajax():
			html=render_to_string(
				template_name="include/results.html",
				context={"filter":blog_filter})
			# blog_filter=BlogFilter(request.GET,queryset=blog_list)
			# data=serializers.serialize('json', blog_filter.qs)
			data_dict={'html_from_view':html}

			return JsonResponse(data=data_dict)
		else:
			blog_filter=BlogFilter(request.GET,queryset=blog_list)
		
	return render(request,'blogger/search.html',{'filter':blog_filter})

class DetailView(generic.DetailView):
	model=Blog
	template_name='blogger/details.html'

def registeration(request):
	form=CreateUserForm()

	if request.method == 'POST':
		form=CreateUserForm(request.POST)
		if form.is_valid():
			form.save()
			user=form.cleaned_data.get('username')
			messages.success(request,'Congratulations! Account is created for ' + user)
			return redirect('/login')

	context={'form':form}
	return render(request,'blogger/registeration.html',context)
	
def login(request):

	if request.method=='POST':
		username=request.POST.get('username')
		password=request.POST.get('password')
		
		user = authenticate(request,username=username, password=password)

		if user is not None:
			auth_login(request,user)
			return redirect('/')
		else:
			messages.info(request,"Username or password is incorrect")

	context = {}
	return render(request,'blogger/login.html',context)

def CategoryView(request,cats):

	category_blogs = Blog.objects.filter(category = cats)
	return render(request,'blogger/categories.html',{'cats':cats,'category_posts':category_blogs})

@login_required(login_url = '/login')
def logout(request):
	auth_logout(request)
	return redirect('/login')

@login_required(login_url = '/login')
def myblogs(request):
	blogs = Blog.objects.filter(author = request.user).order_by('-date')
	context = {'blogs':blogs}
	return render(request,'blogger/myblogs.html',context)
	
@method_decorator(login_required, name = 'dispatch')
class AddblogView(generic.CreateView):
	model = Blog
	form_class = BlogForm
	template_name = 'blogger/addblog.html'

	def post(self,request,*args,**kwargs):
		form = BlogForm(request.POST)
		if form.is_valid():
			
			blog = form.save(commit=False)
			blog.author = request.user
			blog.date = timezone.now()
			blog.save()
   
			# subject="Your post added successfully"
			# message=f'Hi {request.user}!!,Thankk you! Your post has been added successfully!'
			# email_from=settings.EMAIL_HOST_USER
			# recipent_list=[request.user.email]
			# send_mail(subject,message,email_from,recipent_list)
   		
			"""other_subject="New Post Update"
			other_message=f'Hey Everyone! New post has been added by {request.user}! GO and chcekout at our blogsite!! Thank you! Keep blogging.'
			other_email_from=settings.EMAIL_HOST_USER
			bcc=
			mail=EmailMessage(other_subject,other_message,other_email_from,[],bcc)
			mail.send()"""
   			#other_email.send()
			return HttpResponseRedirect('/')
		return render(request,self.template_name,{'form':form})

@method_decorator(login_required, name='dispatch')
class AddcategoryView(generic.CreateView):
	model = Category
	fields = '__all__'
	template_name = 'blogger/addcategory.html'

@method_decorator(login_required, name='dispatch')
class UpdateBlogView(generic.UpdateView):
	model = Blog
	form_class = UpdateBlogForm
	template_name = 'blogger/editblog.html'
	

@method_decorator(login_required, name = 'dispatch')
class DeleteBlogView(generic.DeleteView):
	model = Blog
	template_name = 'blogger/deleteblog.html'
	success_message = "Blog deleted"
	success_url = reverse_lazy('blogger:index')


"""
@method_decorator(login_required, name='dispatch')
class myblogsIndexView(generic.ListView):
	template_name='blogger/myblogs.html'
	context_object_name='users_latest_blog_list'
	paginate_by=5
	
	def get_username(request):
		username = Anonymous
		if request.user.is_authenticated():
			username= self.request.user
		return username
	
	def get_queryset(self):
		uname=get_username(request)
		return Blog.objects.filter(username=uname).order_by('-date')
"""

blogger/templates/blogger/addcategory.html
{% extends "blogger/base.html" %}
{% block title %}Add Blog Category{% endblock %}
{% block content %}
<div class="card">
  <div class="card-header bg-warning">
    Add Blog Category
  </div>
  <div class="card-body">
<div class="form-group">
<form method="POST">
	<table>
	{% csrf_token %}
	{{ form.as_table}}
	</table>
</br>
	 <button type="submit" class="btn btn-primary">Post</button>
	 <a href="{% url 'blogger:index' %}" class="btn btn-dark">Cancel</a>
	</form>
</div>
  </div>
</div>
{% endblock %}

blogger/templates/blogger/base.html
<!DOCTYPE html>
<html>
<head>
  {% load static %}
    <title>{% block title %}Blogger{% endblock %}</title> <meta charset="utf-8">

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=yes">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
  <!--  <script type="text/javascript" src="{% static 'javascript/jquery-3.4.1.min.js' %}"></script>  -->
  <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script> -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>

</head>
<body>
<!-- <form method="get" action="search/" class="form-inline my-2 my-lg-0">
        <div>
          <input class="form-control mr-sm-2 search_box" type="search" placeholder="Search" aria-label="Search" name="search_box" id="query">
          <p class="search-box-error" style="color: red;"></p>
        </div>

        <button class="btn btn-outline-light my-2 my-sm-0 mr-2 btn_search"type="button">Search</button>
      </form>  -->
      
    {% if request.user.is_authenticated %}
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <a class="navbar-brand" href="{% url 'blogger:index' %}">Blogger</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
   
       <ul class="navbar-nav mr-auto nav-pills">
      <li class="nav nav-item btn-dark">
        <a class="nav-link " href="{% url 'blogger:myblogs' %}">My Blogs</a>
      </li>&nbsp&nbsp&nbsp
      
     <!--  <li class="nav-item ">
        <a class="nav-link " href="{% url 'blogger:logout' %}">Logout</a>
      </li> -->
      
     <li class="nav-item btn-dark">
        <a class="nav-link " href="{% url 'blogger:addblog' %}">Add Blog</a>
      </li>&nbsp&nbsp&nbsp

      <li class="nav-item  btn-success ">
        <a class="nav-link " href="{% url 'blogger:addcategory' %}">Add Blog Category</a>
      </li>&nbsp&nbsp&nbsp

      <li class="nav-item  btn-success ">
        <a class="nav-link " href="{% url 'blogger:search' %}">AJAX Search</a>
      </li>
      

    </ul>
  </div>
    <nav class="navbar navbar-success ">
   <div class="dropdown">
        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Hi {{ user.username }}!
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
          <a class="dropdown-item" href="/logout">Log Out</a>
        </div>
      </div>
    </nav>
  </div>
 </nav>
{% endif %}
 {% if not request.user.is_authenticated %}
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'blogger:index' %}">Blogger</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
 
<ul class="nav nav-pills justify-content-end">
 
  <li class="nav-item btn-light">
    <a class="nav-link " href="{% url 'blogger:registeration' %}">Register</a>
  </li>&nbsp&nbsp&nbsp
  <li class="nav-item btn-light">
    <a class="nav-link"href="{% url 'blogger:login'%}">Login</a>
  </li>
 
</ul>
 </div>
</nav>
{% endif %}

    {% block content %}

    {% endblock %}

    {% block footer %}

    <div class="footer">
        <div class="section-inner clearfix">
            <hr>
            <p>&copy;Blogger</p>
        </div>
    </div>

    {% endblock %}

<!-- <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
    integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
    crossorigin="anonymous"></script> -->
    
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
    crossorigin="anonymous"></script>
    <!-- <script type="text/javascript" src="{% static 'javascript/jquery/jquery-3.5.1.js' %}"></script> -->
    <!-- <script type="text/javascript">
    $(document).ready(function(){
      $(".btn_search").on("click", function(event){
        if ($(".search_box").val() != "" && $(".search_box").val() != null && $(".search_box").val() != undefined){
          $(".search-box-error").text("");
          $(".search_box").css({'border': "1px solid #ced4da !important;"});
          //debugger

          $.ajax({
            type: "GET",
            dataType: "json",
            url: "/search",
            data: {"query": $("#query").val()},
          }).then(function(response){
            //debugger
            $(".search-result").html(response.response)
          })
        }else{
          $(".search-box-error").text("");
          $(".search_box").css({'border': "2px solid red"});
          $(".search-box-error").text("Please enter some value!!!")
        }
      })
    })
  </script> -->
</body>
</html>

blogger/templates/blogger/deleteblog.html
{% extends "blogger/base.html" %}
{% block title %}Delete Blog Confirmation{% endblock %}
{% block content %}
<div class="card">
  <div class="card-header bg-warning">
  <h3>Delete: {{blog.blog_name}}</h3>
  </div>
  <div class="card-body">
<h3>Are you sure?</h3>
<form method="POST">
	<table>
	{% csrf_token %}
	
	</table>
</br>
	 <button type="submit" class="btn btn-primary" onclick=" return confirm(' want to delete? ') ">Delete</button>
	 <a href="{% url 'blogger:details' pk=blog.id %}" class="btn btn-dark">Cancel</a>
	</form>

  </div>
</div>
{% endblock %}

blogger/templates/blogger/details.html
{% extends "blogger/details_base.html"  %}

{% block content %}
<div class="card">
  <h3 class="card-header bg-success">{{blog.blog_name}}</h3>
  <div class="card-body">
    <h6 class="card-subtitle mb-2 text-muted">Published on {{blog.date}} by {{blog.author}}</br> Category:{{blog.category}}</h6>
    <p class="card-text">{{blog.blog_text|safe}}</p>
    {% if request.user.is_authenticated and blog.author == request.user %}
    <a href="{% url 'blogger:editblog' pk=blog.pk %}" class="btn btn-dark">Edit</a>
    <a href="{% url 'blogger:deleteblog' pk=blog.pk %}" class="btn btn-dark">Delete</a>
    {% endif %}
    <a href="{% url 'blogger:index' %}" class="btn btn-dark">Go Back</a>
    
    
  </div>
</div>
{% endblock %}

blogger/templates/blogger/details_base.html
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}Blogger{% endblock %}</title> <meta charset="utf-8">

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=yes">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    

</head>
<body>

    {% if request.user.is_authenticated %}
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <a class="navbar-brand" href="{% url 'blogger:index' %}">Blogger</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
   
       <ul class="navbar-nav mr-auto nav-pills">
      <li class="nav nav-item btn-dark">
        <a class="nav-link " href="{% url 'blogger:myblogs' %}">My Blogs</a>
      </li>&nbsp&nbsp&nbsp
      
     <!--  <li class="nav-item ">
        <a class="nav-link " href="{% url 'blogger:logout' %}">Logout</a>
      </li> -->
      
     <li class="nav-item btn-dark">
        <a class="nav-link " href="{% url 'blogger:addblog' %}">Add Blog</a>
      </li>&nbsp&nbsp&nbsp

      <li class="nav-item  btn-success ">
        <a class="nav-link " href="{% url 'blogger:addcategory' %}">Add Blog Category</a>
      </li>
    </ul>
  </div>
    <nav class="navbar navbar-success ">
   <div class="dropdown">
        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Hi {{ user.username }}!
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
          <a class="dropdown-item" href="/logout">Log Out</a>
        </div>
      </div>
    </nav>
  </div>
 </nav>
{% endif %}
 {% if not request.user.is_authenticated %}
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'blogger:index' %}">Blogger</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
 
<ul class="nav nav-pills justify-content-end">
 
  <li class="nav-item btn-light">
    <a class="nav-link " href="{% url 'blogger:registeration' %}">Register</a>
  </li>&nbsp&nbsp&nbsp
  <li class="nav-item btn-light">
    <a class="nav-link"href="{% url 'blogger:login'%}">Login</a>
  </li>
 
</ul>
 </div>
</nav>
{% endif %}

    {% block content %}

    {% endblock %}

    {% block footer %}

    <div class="footer">
        <div class="section-inner clearfix">
            <hr>
            <p>&copy;Blogger</p>
        </div>
    </div>

    {% endblock %}
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
    integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
    crossorigin="anonymous"></script>

</body>
</html>

blogger/templates/blogger/login.html
{% extends "blogger/base.html" %}
{% block content %}
<div class="card">
  <div class="card-header bg-warning">
    Log In
  </div>
  <div class="card-body">
<form action="{% url 'blogger:login' %}" method="POST">
  {% csrf_token %}
  <div class="form-group">
    <label for="exampleInputUsername">Username</label>
    <input type="text" class="form-control" name="username" id="username" aria-describedby="usernameHelp" placeholder="enter username" required/>
      </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Password</label>
    <input type="password" name="password" class="form-control" id="password" placeholder="Password" required/>
  </div>
  
  <button type="submit" class="btn btn-primary">Login</button>
</form>
</div>

{% for message in messages %}
      <p id= messages>{{message}}
{% endfor %}

<div class='nt-4'>
        <div class="d-flex justify-content-left links">
          Don't have an account?<a href="{% url 'blogger:registeration' %}" class="ml-2">register</a>
        </div>
      </div>
</div>
</div>

{% endblock %}

blogger/templates/blogger/search.html
{% extends "blogger/base.html"  %}

{% block content %}

<h3>Search Results</h3>
<div>
<form method="GET" action="">
{{ filter.form }}
  <button type="submit" class="btn btn-primary" id="search_btn">Search</button>
</form></div>

  {# artist-list section #}
  <div id="replaceable-content">
    {% include "include/results.html" %}
    <!-- {% if request.is_ajax == True %}
    {% include "include/results.html" %}
    {% endif } -->
    <!-- {% else %} -->
   <!--  {% if filter.qs %}

  {% for blog in filter.qs %}

    <div class="card-fluid border-danger mb-5 "style="border-color:red">
        <h5 class="card-header bg-warning">{{blog.blog_name}}</h5>
        <div class="card-body">
          <h6 class="card-subtitle mb-2 text-muted">Published on {{blog.date}} by {{blog.author}}</br>
          Category : {{blog.category}}</h6>
          <p class="card-text">{{blog.blog_text|safe}}</p>
          <a href="{% url 'blogger:details' blog.id%}" class="btn btn-dark">Go to Blog</a>
        </div>
    </div>
  {% endfor %}
  
{% else %}
  <p>No blogs are available.</p>
    {% for message in messages %}
      <p id= messages>{{message}}
{% endfor %}
{% endif %}
    {% endif %} -->
    
  </div>

<script type="text/javascript">
    $(document).ready(function(){
      $("#search_btn").click(function(event){
        
          if(($("#id_category")!="" && $("#id_category") != null) || ($("#id_q")!="" && $("#id_q")!=null)){ // $("#1").value="<p>hi</p>";

          $.ajax({type:"GET",dataType:"json",url:"{% url 'blogger:search' %}",data:{"category":$("#id_category").val(),"q":$("#id_q").val()},

            success:function(response){
              
            $("#replaceable-content").html(response.html_from_view) 
            }

          })
            
        }
            event.preventDefault();
        })
      })
  </script>


{% endblock %}